[package]
name = "rust-wasm-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-gc = "0.1.6"

# new material
[lib]
crate-type = ["cdylib", "rlib"]
